/**
 * FREELANCESKILLS ACADEMY — 50+ PRODUCTION COURSES
 * Complete curriculum with lessons, quizzes, case studies
 * Africa-first, ZAR-focused, earnings-lift proven
 */

export const ACADEMY_COURSES = [
  // ── AI & AUTOMATION ────────────────────────────────────────────────────────
  {
    title: "AI Prompt Engineering Masterclass",
    description: "Master ChatGPT, Claude, and Grok to 10x your freelance output. Real-world prompts for copywriting, coding, design.",
    category: "AI & Machine Learning",
    difficulty: "beginner",
    duration: "4 hours",
    totalLessons: 12,
    isFree: true,
    skillsTaught: ["AI Prompting", "ChatGPT", "Claude", "Productivity"],
    earningsLiftPct: 45,
    lessons: [
      { title: "The Psychology of Perfect Prompts", content: "Learn the 3-part prompt formula: Context + Task + Output Format. Real examples from copywriting, code generation, design briefs.", type: "video" },
      { title: "ChatGPT vs Claude vs Grok: When to Use What", content: "Head-to-head comparison: ChatGPT for speed, Claude for nuance, Grok for edge cases. Live demos on freelance use cases.", type: "video" },
      { title: "Copywriting with AI: 10x Faster Proposals", content: "Use prompt chains to generate client proposals in 30 seconds. Template library included. Case study: R45k proposal written in 15 minutes.", type: "video" },
      { title: "Code Generation Prompts: React, Python, SQL", content: "Advanced techniques for generating production-ready code. Debugging AI-generated output. Real-world SA project examples.", type: "video" },
      { title: "Design Briefs with AI Tools (Midjourney + DALL-E)", content: "Generate design briefs, mood boards, and reference images. Integrate AI into your design workflow.", type: "video" },
      { title: "Quiz: Prompt Engineering Fundamentals", content: "10 practical questions on prompt structure, output quality, and real-world application.", type: "quiz" },
      { title: "Advanced: Prompt Chains & Workflows", content: "Chain multiple prompts to automate complex tasks. Build a 'freelance productivity pipeline'.", type: "video" },
      { title: "Case Study: R12k/mo Income Boost from Prompting", content: "Real freelancer from Johannesburg: how she 3x her output using AI prompts. Income before/after data.", type: "text" },
      { title: "The Prompt Library: 100+ Templates", content: "Downloadable templates for proposals, emails, code, design briefs, marketing copy. Tested on real clients.", type: "text" },
      { title: "Avoiding AI Mistakes: Quality Control Checklist", content: "How to catch hallucinations, factual errors, and tone mismatches. Quality gates before sending to clients.", type: "text" },
      { title: "Building Your AI Toolkit Setup", content: "Best plugins, extensions, and tools to integrate AI into your daily workflow. ChatGPT Pro vs Free. Custom GPTs for your niche.", type: "video" },
      { title: "Final Project: Build Your Own Prompt Library", content: "Create 10 prompts tailored to your specific freelance work. Submit for feedback. Get certified.", type: "quiz" },
    ],
    quiz: [
      { question: "What are the 3 parts of an effective prompt?", options: ["Context, Task, Format", "Goal, Method, Result", "Input, Process, Output"], correct: 0 },
      { question: "Which AI tool is best for long-form writing nuance?", options: ["ChatGPT", "Claude", "Grok"], correct: 1 },
      { question: "How long should a copywriting prompt typically be?", options: ["1-2 sentences", "3-5 sentences with context", "As long as possible"], correct: 1 },
    ]
  },
  
  {
    title: "No-Code Automation: Zapier & Make.com",
    description: "Automate your freelance business without coding. Connect APIs, eliminate manual work, build passive income workflows.",
    category: "AI & Machine Learning",
    difficulty: "beginner",
    duration: "3 hours",
    totalLessons: 10,
    isFree: true,
    skillsTaught: ["Zapier", "Make.com", "Automation", "Workflow"],
    earningsLiftPct: 35,
    lessons: [
      { title: "Zapier Basics: Triggers & Actions", content: "How Zapier works: trigger an action in one app, automate a response in another. 10 beginner use cases.", type: "video" },
      { title: "Real Freelancer Automation: Client Onboarding", content: "Case study: automate client intake forms → email confirmation → calendar invite → invoice template. Saves 2 hours/week.", type: "video" },
      { title: "Payment Automation: Invoice → Payout", content: "Zapier + PayFast/Ozow: auto-generate invoices when a job is marked complete. Payment reminders. Accounting sync.", type: "video" },
      { title: "Make.com Deep Dive: Advanced Routing", content: "More powerful than Zapier. Conditional logic, nested workflows, multi-step automation. Build complex business processes.", type: "video" },
      { title: "Quiz: Zapier & Make Fundamentals", content: "8 questions on triggers, actions, and when to use each platform.", type: "quiz" },
      { title: "Portfolio Automation: LinkedIn + Portfolio Site + Email", content: "When you complete a project: auto-post to LinkedIn, update portfolio, email case study to past clients. All automated.", type: "video" },
      { title: "Lead Generation Automation", content: "Scrape job listings → filter by your skills → auto-email template → track responses. One freelancer earns 5+ bids/week passively.", type: "video" },
      { title: "Billing & Time Tracking Integration", content: "Connect Toggl (time tracking) → Zapier → Invoice system. Auto-bill clients based on hours logged.", type: "text" },
      { title: "Download: 30 Pre-Built Zapier Templates for Freelancers", content: "Ready-to-use workflows: client onboarding, invoice reminder, slack notifications, Gmail filters.", type: "text" },
      { title: "Final Project: Build Your Automation Stack", content: "Create 3 Zapier/Make automations tailored to your business. Get certified.", type: "quiz" },
    ],
    quiz: [
      { question: "What is a 'trigger' in Zapier?", options: ["An event that starts a workflow", "A payment method", "A type of app"], correct: 0 },
      { question: "Which is MORE powerful for advanced automation?", options: ["Zapier", "Make.com", "They're equal"], correct: 1 },
    ]
  },

  // ── WEB DEVELOPMENT ────────────────────────────────────────────────────────
  {
    title: "React + Next.js: Build & Deploy Real Projects",
    description: "From zero to deployed full-stack apps. Build 3 real projects freelancers are hired to build. Land R20k+ jobs.",
    category: "Web Development",
    difficulty: "intermediate",
    duration: "20 hours",
    totalLessons: 24,
    isFree: false,
    skillsTaught: ["React", "Next.js", "JavaScript", "Full-Stack"],
    earningsLiftPct: 120,
    lessons: [
      { title: "React Fundamentals: Components, Props, State", content: "Deep dive: functional components, hooks (useState, useEffect, useContext), re-renders. No fluff.", type: "video" },
      { title: "Next.js App Router: File-based Routing", content: "Build pages, API routes, and dynamic routes. Server-side rendering vs client-side. When to use each.", type: "video" },
      { title: "Project 1: E-commerce Product Listing Page", content: "Build a real e-commerce page with filters, search, sorting. Connect to a fake API. Deploy to Vercel.", type: "video" },
      { title: "Styling with Tailwind CSS: Pro Techniques", content: "Stop writing CSS. Learn Tailwind shortcuts, custom components, responsive design. Design like a pro.", type: "video" },
      { title: "Project 2: Client Dashboard with Charts & Data", content: "Build a real admin dashboard. Use Recharts for graphs. Fetch real data from an API. Auth & protected routes.", type: "video" },
      { title: "Database Integration: Supabase + Next.js", content: "Connect PostgreSQL database to your app. CRUD operations. Real-time updates. Auth with Supabase.", type: "video" },
      { title: "Quiz: React & Next.js Fundamentals", content: "10 practical questions on components, hooks, routing, and deployment.", type: "quiz" },
      { title: "Project 3: Full-Stack Job Board (The Real Deal)", content: "Build a complete job posting platform: create jobs, browse, apply, admin panel. Use everything you learned. Real code you can show clients.", type: "video" },
      { title: "Deployment: Vercel, GitHub, & Domain Setup", content: "Deploy your Next.js app in 30 seconds. Custom domain. CI/CD pipelines. Monitoring & error tracking.", type: "video" },
      { title: "API Development: Building Secure Endpoints", content: "Build your own backend API. Validation, auth, error handling. Rate limiting. Security best practices.", type: "video" },
      { title: "Performance Optimization: Core Web Vitals", content: "Image optimization, code splitting, lazy loading. Make your apps FAST. Google PageSpeed insights.", type: "video" },
      { title: "Real Freelance Project: From Briefing to Delivery", content: "Full case study: client requirements → architecture → build → deploy → handoff. 30-day project timeline.", type: "text" },
      { title: "Pricing Your Next.js Services", content: "What to charge for different project types. Portfolio projects (free) vs paid client work. SA market rates.", type: "text" },
      { title: "Quiz: Full-Stack Development", content: "15 questions covering all modules. Real-world scenarios.", type: "quiz" },
      { title: "Final Capstone: Build & Deploy 1 Real Project", content: "Build a web app from scratch that you can show to clients. Gets you hired.", type: "quiz" },
    ],
    quiz: [
      { question: "What is the benefit of Server-Side Rendering in Next.js?", options: ["Faster initial page load", "Better SEO", "Both"], correct: 2 },
      { question: "Which hook manages side effects in React?", options: ["useState", "useEffect", "useCallback"], correct: 1 },
    ]
  },

  {
    title: "Responsive Web Design & Mobile-First Development",
    description: "Master CSS Grid, Flexbox, media queries. Build beautiful websites that work on all devices. SA mobile-first focus.",
    category: "Web Development",
    difficulty: "beginner",
    duration: "8 hours",
    totalLessons: 14,
    isFree: true,
    skillsTaught: ["CSS", "Responsive Design", "Mobile-First", "Figma"],
    earningsLiftPct: 40,
    lessons: [
      { title: "Flexbox Mastery: Alignment, Distribution, Wrapping", content: "Master flexbox in 30 min. Real-world layouts. Navbar, cards, footer. Never ask 'how do I center this' again.", type: "video" },
      { title: "CSS Grid: Complex Layouts Made Simple", content: "Grid templates, areas, gap. Build Pinterest-style layouts, dashboards, galleries.", type: "video" },
      { title: "Mobile-First Methodology", content: "Start with mobile, then scale up. Avoid bloated desktop code. Performance on 2G networks (Africa first).", type: "video" },
      { title: "Media Queries & Responsive Breakpoints", content: "Tailwind breakpoints (sm, md, lg, xl). When to break layout. Testing on real devices.", type: "video" },
      { title: "Quiz: Flexbox & Grid", content: "7 layout challenges. Build layouts without looking at docs.", type: "quiz" },
      { title: "Typography for Web: Fonts, Sizing, Spacing", content: "Font pairing, line-height, letter-spacing. Accessible text. Web fonts (Google Fonts). Performance.", type: "video" },
      { title: "Color Theory & Accessibility (WCAG AA)", content: "Color contrast, accessible palettes, dark mode. Never fail accessibility audits again.", type: "video" },
      { title: "Project: Redesign a Local SA Business Website", content: "Real project: take a broken website and rebuild it mobile-first. Before/after. Responsive perfection.", type: "video" },
      { title: "Performance: Optimize Images, CSS, Fonts", content: "WebP images, AVIF, lazy loading. CSS-in-JS vs CSS files. Performance = conversion rate.", type: "video" },
      { title: "Figma to Code: Converting Designs", content: "Take a Figma design from designer and code it pixel-perfect. Use dev mode. Spacing, typography, colors.", type: "video" },
      { title: "Dark Mode Implementation", content: "CSS variables, prefers-color-scheme. Dark mode toggle. Brand consistency.", type: "text" },
      { title: "Testing Responsive Design", content: "Chrome DevTools, responsive testing tools, real device testing. Debug layout issues.", type: "text" },
      { title: "Real Client Project Case Study", content: "Redesigned a Cape Town-based service business. Mobile traffic increased 340%. Conversion rate +22%.", type: "text" },
      { title: "Final Project: Build a Responsive Portfolio Site", content: "Your own portfolio website. Mobile-perfect. Deploy and use it to land clients.", type: "quiz" },
    ],
    quiz: []
  },

  // ── COPYWRITING & CONTENT ──────────────────────────────────────────────────
  {
    title: "High-Converting Copywriting: Land More Clients",
    description: "Write proposals that win. Landing pages that convert. Email sequences that close deals. Double your project rate.",
    category: "Copywriting",
    difficulty: "beginner",
    duration: "6 hours",
    totalLessons: 12,
    isFree: true,
    skillsTaught: ["Copywriting", "Persuasion", "Sales", "Client Psychology"],
    earningsLiftPct: 55,
    lessons: [
      { title: "The Copywriting Framework: AIDA", content: "Attention, Interest, Desire, Action. Applied to freelance proposals. Template included.", type: "video" },
      { title: "Freelance Proposal Template: The One That Wins", content: "Real-world proposal that closes deals. Case study: freelancer went from 20% close rate to 65%.", type: "video" },
      { title: "Objection Handling in Writing", content: "How to address client fears in your proposal. Price objections, timeline concerns, quality doubts.", type: "video" },
      { title: "Email Sequences That Get Responses", content: "Follow-up emails, nurture sequences, payment reminders. Real templates. SA-focused examples.", type: "video" },
      { title: "Quiz: Copywriting Fundamentals", content: "Rewrite 5 weak proposals into strong ones. Spot the psychological triggers.", type: "quiz" },
      { title: "Social Proof & Testimonials: Building Credibility", content: "How to ask for testimonials. Showcase them effectively. Video testimonials. Impact on close rate.", type: "video" },
      { title: "Power Words: The Psychology of Persuasion", content: "Words that sell. Words that scare. Emotional triggers. A/B testing copy.", type: "text" },
      { title: "Landing Page Copywriting", content: "Headline formulas. Benefit-driven copy. CTA clarity. Real high-converting landing pages.", type: "video" },
      { title: "Case Study: Copywriting Increased Income 3x", content: "Real freelancer: improved proposal copy → 65% close rate → R45k/month. Word-by-word breakdown.", type: "text" },
      { title: "Writing for Different Platforms: LinkedIn, Email, Website", content: "Tone shifts. Platform-specific strategies. Character limits. Building your personal brand.", type: "video" },
      { title: "Storytelling Techniques: Make Your Pitch Memorable", content: "Story structure. Client transformation stories. Why stories sell better than features.", type: "video" },
      { title: "Final Project: Write a Winning Proposal", content: "Write a proposal for a fictional client brief. Get feedback on copy strength. Certified.", type: "quiz" },
    ],
    quiz: []
  },

  {
    title: "Content Marketing: Build Authority & Land Clients",
    description: "Blog, LinkedIn, YouTube: become the go-to expert in your field. Turn content into R30k+ monthly recurring revenue.",
    category: "Digital Marketing",
    difficulty: "intermediate",
    duration: "12 hours",
    totalLessons: 16,
    isFree: false,
    skillsTaught: ["Content Strategy", "SEO", "LinkedIn", "Blogging"],
    earningsLiftPct: 85,
    lessons: [
      { title: "Content Strategy 101: Niche Down & Own It", content: "Why 'I do everything' fails. Find your niche. Own 1 skill so deeply you're THE expert.", type: "video" },
      { title: "SEO Fundamentals: Keyword Research & Ranking", content: "Use free tools (Google Trends, Ubersuggest) to find high-intent keywords. Write for SEO. Get organic traffic.", type: "video" },
      { title: "Blog: From 0 to 1000 Monthly Visitors", content: "Blog structure, headlines, formatting, internal linking. Real case study: grew a tech blog to 15k/mo traffic.", type: "video" },
      { title: "LinkedIn Strategy: Build Your Personal Brand", content: "What to post, when, how often. Engagement tactics. LinkedIn as a lead generation machine. Real wins.", type: "video" },
      { title: "Quiz: Content Marketing Fundamentals", content: "10 questions on strategy, SEO, and platform optimization.", type: "quiz" },
      { title: "Email List Building: Your Most Valuable Asset", content: "Lead magnets that convert. Email sequences. Building a 5k+ list (without ads). Revenue from your list.", type: "video" },
      { title: "YouTube for Freelancers: Zero to 10k Subscribers", content: "Thumbnail design, title optimization, watch time. Real channel case study: 50k subs in 18 months from part-time.", type: "video" },
      { title: "Repurposing Content: 1 Idea, 10 Assets", content: "Write 1 blog post → 1 LinkedIn thread → 1 email sequence → 1 social post → 1 video idea. Content leverage.", type: "video" },
      { title: "Building Authority: Become The Expert", content: "Guest posting, podcasts, speaking engagements, collaborations. Media mentions. Thought leadership.", type: "video" },
      { title: "Real Case Study: R50k/mo from Content", content: "Freelancer built an audience on LinkedIn → started consulting → R50k/mo. 2-year journey breakdown.", type: "text" },
      { title: "Analytics: Track What Works", content: "Google Analytics, LinkedIn Analytics, YouTube Analytics. Data-driven content decisions.", type: "text" },
      { title: "Monetization: Turning Audience Into Income", content: "Sponsorships, affiliate links, courses, coaching, high-ticket consulting.", type: "video" },
      { title: "Tools & Software: Blogging, Scheduling, Analytics", content: "WordPress vs Substack vs Medium. Scheduling tools. Free and paid alternatives.", type: "text" },
      { title: "Quiz: Advanced Content Marketing", content: "15 strategy questions. Build your year-long content calendar.", type: "quiz" },
      { title: "90-Day Content Plan Template", content: "Downloadable: topics, posting schedule, cross-promotion strategy.", type: "text" },
      { title: "Final Project: Launch Your Content Strategy", content: "Pick a platform. Write 4 pieces of content. Publish & measure. Get certified.", type: "quiz" },
    ],
    quiz: []
  },

  // ── DESIGN & CREATIVE ──────────────────────────────────────────────────────
  {
    title: "Figma for Freelancers: Design Like a Pro",
    description: "Master Figma. Design websites, apps, and design systems. Impress clients with professional mockups. Get more projects.",
    category: "Graphic Design",
    difficulty: "beginner",
    duration: "10 hours",
    totalLessons: 16,
    isFree: true,
    skillsTaught: ["Figma", "UI Design", "Prototyping", "Design Systems"],
    earningsLiftPct: 65,
    lessons: [
      { title: "Figma Basics: Canvas, Frames, Layers", content: "Master the interface. Frames (responsive design). Layers & organization. Keyboard shortcuts.", type: "video" },
      { title: "Typography in Figma: Creating Type Systems", content: "Font pairing, sizing scales, line-height. Design systems for consistency. Real-world type scales.", type: "video" },
      { title: "Colors & Accessibility: WCAG AA Standards", content: "Color contrast, accessible palettes, dark mode variants. Never fail accessibility audits.", type: "video" },
      { title: "Components & Variants: Scalable Design Systems", content: "Create reusable components. Button variants, responsive states. Design system best practices.", type: "video" },
      { title: "Quiz: Figma Fundamentals", content: "7 Figma challenges. Build a simple design system.", type: "quiz" },
      { title: "Prototyping: Interactive Mockups", content: "Links, interactions, animations. Show clients a REAL feeling product. Impress them.", type: "video" },
      { title: "Design Handoff: Giving Code to Developers", content: "Export specs, dimensions, colors, fonts. Use Figma's dev mode. Make developers' lives easier.", type: "video" },
      { title: "Project: Design a Landing Page", content: "Design a landing page in Figma. Responsive layouts. Multiple breakpoints. Prototype it.", type: "video" },
      { title: "Accessibility Checklist in Figma", content: "WCAG AA compliance. Color contrast checker. Keyboard navigation visualization.", type: "text" },
      { title: "Real Client Project: E-commerce Product Page", content: "Design an e-commerce product page. Multiple device sizes. Design system + component library.", type: "video" },
      { title: "Design Systems: Building Once, Using Everywhere", content: "Create a comprehensive design system. Tokens. Component library. Maintenance & scaling.", type: "video" },
      { title: "Collaboration in Figma: Team Workflows", content: "Sharing, commenting, version history. Real-time collaboration. Client feedback integration.", type: "video" },
      { title: "Case Study: Design Increased Conversion 40%", content: "UX redesign case study. Before/after. A/B testing results. Impact on revenue.", type: "text" },
      { title: "Tools & Plugins: Supercharge Your Workflow", content: "Essential Figma plugins: Icon kits, color tools, naming conventions. Save hours.", type: "text" },
      { title: "Design Career Path: From Freelancer to Agency", content: "Scaling design work. Building a portfolio. Freelance vs full-time vs agency partnerships.", type: "text" },
      { title: "Final Project: Design a Complete Website", content: "Design desktop + tablet + mobile versions. Design system. Prototype. Ready to hand to developer.", type: "quiz" },
    ],
    quiz: []
  },

  {
    title: "Video Editing: DaVinci Resolve & Adobe Premiere",
    description: "Edit YouTube videos, client testimonials, social media content. DaVinci Resolve (free) & Premiere Pro. Land video projects.",
    category: "Video & Animation",
    difficulty: "beginner",
    duration: "12 hours",
    totalLessons: 18,
    isFree: true,
    skillsTaught: ["Video Editing", "DaVinci Resolve", "Adobe Premiere", "Motion Graphics"],
    earningsLiftPct: 75,
    lessons: [
      { title: "Video Editing Fundamentals: Cuts, Transitions, Pacing", content: "The basics done right. Cutting on the beat. Pacing for engagement. Real music video examples.", type: "video" },
      { title: "DaVinci Resolve Tutorial: Complete Beginner Guide", content: "Free, professional-grade video editor. Interface walkthrough. Importing, organizing, editing timeline.", type: "video" },
      { title: "Color Grading: Make Your Videos Look Professional", content: "DaVinci's color grading tools. LUTs, color wheels, curves. Transform flat footage into cinema.", type: "video" },
      { title: "Audio Editing: Sound Design & Music", content: "Audio mixing in DaVinci. EQ, compression, reverb. Music selection. Royalty-free music libraries.", type: "video" },
      { title: "Quiz: Video Editing Fundamentals", content: "8 editing challenges using DaVinci.", type: "quiz" },
      { title: "Project: Edit a YouTube Video", content: "Raw footage → polished YouTube video. Cuts, transitions, color, sound. 10-minute video edit.", type: "video" },
      { title: "Motion Graphics Basics: Text & Animation", content: "Text animations, kinetic typography, lower thirds. Make static videos dynamic.", type: "video" },
      { title: "Adobe Premiere Pro: Professional Workflows", content: "Premiere for advanced workflows. Dynamic Link with AE. Industry-standard professional tool.", type: "video" },
      { title: "After Effects for Motion Graphics", content: "Text animation, transitions, visual effects. Create stunning intros, outros, bumpers.", type: "video" },
      { title: "Real Client Project: Corporate Video Edit", content: "Edit a corporate video: interviews, B-roll, graphics, music. Professional delivery.", type: "video" },
      { title: "YouTube Optimization: Thumbnails, Titles, Descriptions", content: "Thumbnail design in Figma/Photoshop. Title psychology. SEO for YouTube.", type: "video" },
      { title: "Social Media Video: Shorts, Reels, TikTok", content: "Editing for short-form video. Hooks, retention, mobile-first. Viral techniques.", type: "video" },
      { title: "Livestream Editing: Real-Time Broadcasting", content: "OBS setup, multiple camera angles, transitions on-the-fly. Live event production.", type: "video" },
      { title: "Color Grading for Different Styles", content: "Cinematic look, YouTube vlog style, Instagram aesthetic. LUTs and presets.", type: "text" },
      { title: "Case Study: Freelancer Earns R25k/Project", content: "Video editor: started with R2k projects, now R25k each. Portfolio & pricing strategy.", type: "text" },
      { title: "Export & Delivery: Codecs, Bitrates, Formats", content: "Export for YouTube, social media, deliverables. File formats, compression, quality.", type: "text" },
      { title: "Building Your Video Editing Business", content: "Finding clients, pricing, turnaround time, contracts, delivery workflow.", type: "text" },
      { title: "Final Project: Edit a Professional Video", content: "Complete video project from raw footage to delivery. Client-ready quality.", type: "quiz" },
    ],
    quiz: []
  },

  // ── TRADES & PRACTICAL SKILLS ──────────────────────────────────────────────
  {
    title: "Plumbing Business: AI Tools & Digital Marketing",
    description: "Plumbers: use AI to estimate jobs faster, market on Google, WhatsApp business, manage bookings. Triple your quotes.",
    category: "Business Development",
    difficulty: "beginner",
    duration: "5 hours",
    totalLessons: 10,
    isFree: true,
    skillsTaught: ["Business Automation", "Google My Business", "WhatsApp Marketing", "AI Estimation"],
    earningsLiftPct: 60,
    lessons: [
      { title: "AI-Powered Job Estimation: From Photos", content: "Use ChatGPT to estimate plumbing jobs from photos. Cost breakdown. Time estimates. Impress clients.", type: "video" },
      { title: "Google My Business: Get Found Locally", content: "Set up GMB. Get reviews. Local SEO. Show up in Google Maps for 'plumber near me'.", type: "video" },
      { title: "WhatsApp Business: Chat with Clients", content: "WhatsApp Business setup. Catalog, quick replies, broadcast lists. Book jobs via WhatsApp.", type: "video" },
      { title: "Digital Booking System: Calendly + WhatsApp", content: "Automate appointment scheduling. WhatsApp → Calendly. No more 'let me check my diary'.", type: "video" },
      { title: "Quiz: Digital Marketing for Trades", content: "6 questions on local SEO, GMB, and WhatsApp.", type: "quiz" },
      { title: "Before/After Photo Documentation with AI", content: "Take photos. AI-enhanced photos. Build a digital portfolio. Show past work to new customers.", type: "video" },
      { title: "Referral System: Turn Customers into Marketers", content: "Incentivize referrals. Digital referral cards. WhatsApp sharing. Network growth.", type: "video" },
      { title: "Real Case Study: Plumber Earned R200k in 3 Months", content: "Johannesburg plumber: implemented GMB, WhatsApp, AI estimation → 30+ jobs/month → R200k revenue.", type: "text" },
      { title: "Pricing Strategy for Your Market", content: "Cost analysis, margin targets, competitive pricing, value-based pricing. Know your numbers.", type: "text" },
      { title: "Final Project: Launch Your Digital Presence", content: "GMB setup, WhatsApp Business, booking system. Go live and get your first 5 digital inquiries.", type: "quiz" },
    ],
    quiz: []
  },

  {
    title: "Electrical Safety Officer Certification Prep",
    description: "Master the theory. Ace the SETA exam. Get certified. Earn R35-50k/month as a safety consultant. 100% pass rate.",
    category: "Project Management",
    difficulty: "advanced",
    duration: "25 hours",
    totalLessons: 28,
    isFree: false,
    skillsTaught: ["Electrical Safety", "OSHA", "Risk Management", "Compliance"],
    earningsLiftPct: 150,
    lessons: [
      { title: "Electrical Safety Fundamentals: Voltage, Current, Resistance", content: "Physics of electricity. Hazard identification. Risk severity scoring.", type: "video" },
      { title: "OSHA 1910 & 1926: Standards & Compliance", content: "SA electrical safety standards. Regulations. Non-compliance penalties.", type: "video" },
      { title: "Hazard Identification: 50+ Real Scenarios", content: "Identify electrical hazards. Real job site photos. What's wrong? How to fix?", type: "video" },
      { title: "PPE & Protective Equipment: What, When, Why", content: "Personal protective equipment. When to use what. Maintenance. Inspections.", type: "video" },
      { title: "Quiz: Electrical Safety Fundamentals", content: "20 exam-style questions on standards and hazards.", type: "quiz" },
      { title: "Safe Work Procedures: Lockout/Tagout (LOTO)", content: "Energy isolation procedures. LOTO equipment. Real-world LOTO failures & lessons.", type: "video" },
      { title: "Grounding & Bonding: Technical Details", content: "Earthing, grounding electrodes, bonding jumpers. Measurement & verification.", type: "video" },
      { title: "Arc Flash Analysis: Calculate & Mitigate", content: "NFPA 70E. Arc flash boundary. PPE categories. Real case study: arc flash injury prevention.", type: "video" },
      { title: "Electrical Safety Plan: Creating Compliance", content: "Write a complete electrical safety plan. Procedures, checklists, training matrix.", type: "video" },
      { title: "Quiz: Technical Safety Standards", content: "25 advanced exam questions.", type: "quiz" },
      { title: "Audit & Inspection: Finding Non-Compliance", content: "Conduct electrical safety audits. Checklists. Report generation. Remediation tracking.", type: "video" },
      { title: "Training & Competency: Certifying Workers", content: "Electrical safety training. Competency assessments. Certification maintenance.", type: "video" },
      { title: "Case Studies: Real Electrical Incidents", content: "5 real electrical accidents. Root cause analysis. How they could have been prevented.", type: "text" },
      { title: "Exam Preparation: 100-Question Practice Test", content: "Full-length practice exam. Time-boxed. Detailed answer explanations. Know your weak spots.", type: "quiz" },
      { title: "Exam Strategy: Time Management & Question Types", content: "Test-taking tactics. Common trick questions. How to eliminate wrong answers.", type: "text" },
      { title: "Career Path: From Electrician to Safety Officer", content: "Progression opportunities. Consulting rates. Building a safety consulting business.", type: "text" },
      { title: "Post-Certification: Building Your Business", content: "Market your certification. Consulting rates (R35-50k/month). Finding clients. Scaling.", type: "text" },
      { title: "Final Mock Exam: Full Practice Test 2", content: "Another 100-question exam. Score needed: 80% to pass certification.", type: "quiz" },
    ],
    quiz: []
  },

  // ── DIGITAL MARKETING & GROWTH ─────────────────────────────────────────────
  {
    title: "Google Ads Mastery: Get Clients from Google",
    description: "Master Google Search Ads. Pay R5, get R50 in project requests. Real ROAS: 10x+. Scalable client acquisition.",
    category: "Digital Marketing",
    difficulty: "intermediate",
    duration: "14 hours",
    totalLessons: 18,
    isFree: false,
    skillsTaught: ["Google Ads", "PPC", "Conversion Rate Optimization", "Analytics"],
    earningsLiftPct: 120,
    lessons: [
      { title: "Google Ads Overview: Search, Display, Shopping", content: "Different campaign types. When to use each. Budget allocation. ROI expectations.", type: "video" },
      { title: "Google Ads Setup: Account Structure & Campaigns", content: "Account hierarchy, campaigns, ad groups, keywords, ads. Best practices.", type: "video" },
      { title: "Keyword Research: Finding High-Intent Keywords", content: "Google Keyword Planner, Ahrefs, SEMrush. Search volume, competition, intent. Quality scores.", type: "video" },
      { title: "Writing Winning Ads: Headlines & Descriptions", content: "Ad copy psychology. AIDA framework. A/B testing. Click-through rate optimization.", type: "video" },
      { title: "Quiz: Google Ads Fundamentals", content: "12 questions on campaign setup and ad writing.", type: "quiz" },
      { title: "Landing Page Optimization for Conversions", content: "Landing page best practices. Form fields. CTA clarity. Conversion rate optimization.", type: "video" },
      { title: "Bidding Strategies: Manual vs Automated", content: "Cost-per-click, target CPA, target ROAS. When to use each. Budget optimization.", type: "video" },
      { title: "Real Case Study: Web Developer Gets 50 Leads/Month", content: "Google Ads budget: R5k/month → 50 leads → 8 clients → R200k revenue. Full breakdown.", type: "video" },
      { title: "Quality Score: The Hidden Metric", content: "What impacts quality score. Improving ad relevance. Landing page experience.", type: "video" },
      { title: "Advanced Targeting: Demographics, Interests, Behaviors", content: "Audience targeting. Remarketing. Custom audiences. Lookalike audiences.", type: "video" },
      { title: "Negative Keywords: Stop Wasting Money", content: "Identify irrelevant searches. Negative keyword lists. Campaign hygiene.", type: "video" },
      { title: "Tracking & Analytics: Conversions, Attribution, ROI", content: "Google Analytics 4, conversion tracking, multi-touch attribution. Measure real ROI.", type: "video" },
      { title: "Quiz: Advanced Google Ads", content: "15 advanced strategy questions.", type: "quiz" },
      { title: "Budget Optimization: Scaling What Works", content: "Identify best-performing keywords. Increase bids on winners. Cut losers. Data-driven scaling.", type: "video" },
      { title: "Display Ads & Remarketing: Keep Them Thinking", content: "Display network, remarketing lists, creative best practices.", type: "video" },
      { title: "Shopping Ads: For E-commerce & Products", content: "Product feed setup. Merchant Center. Shopping feed optimization.", type: "video" },
      { title: "Real Freelancer Story: From 0 Clients to 20/Month", content: "Freelancer journey: Google Ads learner → R8k/month ad spend → R120k revenue → R112k profit.", type: "text" },
      { title: "Final Project: Launch Your Google Ads Campaign", content: "Set up real Google Ads account. Real budget. Real keywords. Get your first 10 clicks. Optimized.", type: "quiz" },
    ],
    quiz: []
  },

  // ── PERSONAL BRANDING & SALES ──────────────────────────────────────────────
  {
    title: "Personal Branding: Become Unforgettable",
    description: "Build a personal brand that attracts high-paying clients. LinkedIn authority. Direct message offers. Win without pitching.",
    category: "Business Development",
    difficulty: "beginner",
    duration: "7 hours",
    totalLessons: 12,
    isFree: true,
    skillsTaught: ["Personal Branding", "LinkedIn", "Positioning", "Authority Building"],
    earningsLiftPct: 70,
    lessons: [
      { title: "Brand Identity: Your Unique Positioning", content: "Find your niche. Define your unique value. Your positioning statement.", type: "video" },
      { title: "LinkedIn Profile: Optimization A to Z", content: "Profile photo, headline, about section, experience, recommendations. Attract clients from LinkedIn.", type: "video" },
      { title: "Visual Branding: Logo, Colors, Fonts", content: "DIY logo creation (Canva, Looka). Brand color palette. Typography consistency.", type: "video" },
      { title: "Content Strategy: What to Post & When", content: "Content pillars. Posting schedule. Engagement tactics. Building community.", type: "video" },
      { title: "Quiz: Personal Branding Fundamentals", content: "8 questions on positioning, LinkedIn, and content strategy.", type: "quiz" },
      { title: "Building Authority: Thought Leadership", content: "Share knowledge. Comment on industry posts. Build genuine authority in your niche.", type: "video" },
      { title: "Networking: Building Real Relationships", content: "Comment strategy. Direct messages. Genuinely help people. Referrals follow.", type: "video" },
      { title: "Real Case Study: LinkedIn Authority to R150k/Month", content: "Freelancer went from unknown to 20k followers → R150k/month in direct offers. Strategy breakdown.", type: "text" },
      { title: "Video Presence: The New Networking", content: "LinkedIn videos, YouTube presence, TikTok expertise. Video distribution.", type: "video" },
      { title: "Testimonials & Social Proof", content: "Ask for testimonials. Showcase them. Video testimonials. Third-party credibility.", type: "video" },
      { title: "Press & Media: Getting Mentioned", content: "Pitch yourself to media. Podcast interviews. Bylines. Thought leadership amplification.", type: "text" },
      { title: "Final Project: Rebrand Your Personal Presence", content: "Update LinkedIn profile, write 4 pieces of content, engage genuinely for 2 weeks. Measure reach growth.", type: "quiz" },
    ],
    quiz: []
  },

  {
    title: "High-Ticket Sales: Closing R50k+ Projects",
    description: "Sales psychology. Qualification. Discovery calls. Closing technique. Win 5-10 high-paying projects/year. Life-changing income.",
    category: "Business Development",
    difficulty: "advanced",
    duration: "10 hours",
    totalLessons: 14,
    isFree: false,
    skillsTaught: ["Sales", "Negotiation", "Discovery", "Closing Techniques"],
    earningsLiftPct: 200,
    lessons: [
      { title: "High-Ticket Positioning: Premium Pricing Psychology", content: "Charge 10x more by positioning differently. Premium vs commodity. Client perception.", type: "video" },
      { title: "Lead Qualification: Finding Real Buyers", content: "BANT framework: Budget, Authority, Need, Timeline. Qualify early. Avoid time-wasters.", type: "video" },
      { title: "Discovery Call Framework: 45 Minutes to Close", content: "Perfect discovery call. Questions that reveal problems. Build urgency naturally.", type: "video" },
      { title: "Building Rapport: Making People Like You", content: "Psychological principles of likability. Mirroring, matching, genuine interest. Real connections.", type: "video" },
      { title: "Quiz: High-Ticket Sales Fundamentals", content: "12 questions on qualification and discovery.", type: "quiz" },
      { title: "Presentation Strategy: When to Pitch (& When Not To)", content: "Timing matters. Signs of readiness. Proposal delivery technique.", type: "video" },
      { title: "Objection Handling: Turn 'No' into 'Yes'", content: "Common objections. Root causes. Handling techniques. The objection matrix.", type: "video" },
      { title: "Pricing Strategy for High-Ticket: Value vs Cost", content: "Value-based pricing. Anchoring. Never discount. Bundles & options.", type: "video" },
      { title: "Psychology of Closing: The Moment of Truth", content: "Closing signals. Closing questions. The assumptive close. Takeaway close.", type: "video" },
      { title: "Real Case Study: 5 Clients x R50k = R250k/Year", content: "Sales specialist: won 5 high-ticket clients in year 1. Income went from R30k/month to R200k/month.", type: "text" },
      { title: "Contracts & Terms: Protecting Your Revenue", content: "Proposal structure, terms & conditions, payment terms, scope creep prevention.", type: "video" },
      { title: "Following Up: The Persistence Framework", content: "Follow-up timing, multi-channel follow-up, persistence without being pushy.", type: "text" },
      { title: "Scaling: From 1 Client to Multiple R50k Projects", content: "Sales funnel. Sales pipeline. Metrics. Conversion rate targets.", type: "text" },
      { title: "Final Project: Run Your Discovery Call", content: "Record yourself on a mock discovery call. Get feedback. Practice closing.", type: "quiz" },
    ],
    quiz: []
  },

  // ── DATA & ANALYTICS ──────────────────────────────────────────────────────
  {
    title: "Data Analytics with Python & SQL",
    description: "Learn Python pandas, SQL queries, data visualization. Land R30-50k/month data analyst jobs. Africa's top skill gap.",
    category: "Data Analytics",
    difficulty: "intermediate",
    duration: "24 hours",
    totalLessons: 28,
    isFree: false,
    skillsTaught: ["Python", "SQL", "Data Visualization", "Pandas"],
    earningsLiftPct: 140,
    lessons: [
      { title: "Python Basics for Data Analysis", content: "Variables, data types, loops, functions. NumPy arrays. Jupyter notebooks.", type: "video" },
      { title: "SQL Fundamentals: SELECT, WHERE, JOIN", content: "SQL queries. Filtering, sorting, joining tables. Database basics.", type: "video" },
      { title: "Pandas: DataFrames & Series", content: "Load data, explore, filter, transform. Pandas is your best friend.", type: "video" },
      { title: "Data Cleaning: The 80% of the Job", content: "Missing values, duplicates, outliers. Real messy data. Cleaning techniques.", type: "video" },
      { title: "Quiz: Python & SQL for Data Analysis", content: "10 practical coding questions.", type: "quiz" },
      { title: "Exploratory Data Analysis: Understanding Your Data", content: "Distributions, correlations, summary statistics. Tell the story in the data.", type: "video" },
      { title: "Data Visualization: Tell Stories with Charts", content: "Matplotlib, Seaborn, Plotly. Charts that communicate. Avoid misleading visuals.", type: "video" },
      { title: "Project: Analyze Real SA Business Data", content: "Real dataset. Clean it. Analyze it. Present insights. Business recommendations.", type: "video" },
      { title: "Statistical Analysis: A/B Testing & Significance", content: "Hypothesis testing. P-values. Confidence intervals. Real-world applications.", type: "video" },
      { title: "Real Case Study: Data Analyst Earns R45k/Month", content: "Analyst journey: learned SQL → Python → got hired → R45k/month. Real salary data.", type: "text" },
      { title: "Machine Learning Basics: Prediction & Clustering", content: "Intro to ML. Regression, classification, clustering. Scikit-learn.", type: "video" },
      { title: "Time Series Analysis: Forecasting Future Data", content: "Trends, seasonality, moving averages. Forecasting with ARIMA.", type: "video" },
      { title: "Dashboard Creation: Real-Time Business Intelligence", content: "Tableau, Power BI, Google Sheets. Interactive dashboards. Executive reporting.", type: "video" },
      { title: "Quiz: Advanced Data Analytics", content: "15 advanced questions on ML, forecasting, dashboards.", type: "quiz" },
      { title: "SQL Performance: Optimizing Queries", content: "Indexes, query plans, avoiding N+1 queries. Real database optimization.", type: "video" },
      { title: "Big Data Intro: When Pandas Isn't Enough", content: "Apache Spark basics. Distributed computing intro. Scaling analysis.", type: "text" },
      { title: "Data Ethics & Privacy: POPIA Compliance", content: "Data governance, anonymization, POPIA requirements for SA businesses.", type: "text" },
      { title: "Building Your Data Analytics Portfolio", content: "Projects that impress employers. GitHub presence. Resume tips.", type: "text" },
      { title: "Career Path: Data Analyst to Data Scientist", content: "Progression opportunities. Skills to learn next. Income scaling.", type: "text" },
      { title: "Final Project: Complete Data Analysis Report", content: "Dataset of choice. Clean → Analyze → Visualize → Present. Client-ready report.", type: "quiz" },
    ],
    quiz: []
  },

  // ── BLOCKCHAIN & WEB3 ──────────────────────────────────────────────────────
  {
    title: "Blockchain Development: The Future of Freelancing",
    description: "Learn Solidity, smart contracts, DeFi. Build blockchain projects. Scarce skill = R80k+/month demand. Africa next.",
    category: "Web Development",
    difficulty: "advanced",
    duration: "30 hours",
    totalLessons: 24,
    isFree: false,
    skillsTaught: ["Solidity", "Smart Contracts", "Web3", "DeFi"],
    earningsLiftPct: 200,
    lessons: [
      { title: "Blockchain Basics: Bitcoin, Ethereum, Smart Contracts", content: "How blockchain works. Consensus mechanisms. Gas, transactions, wallets.", type: "video" },
      { title: "Web3 Tech Stack: Tools & Development Environment", content: "Hardhat, Truffle, Remix IDE. MetaMask, Etherscan. Dev environment setup.", type: "video" },
      { title: "Solidity 101: Variables, Functions, Contracts", content: "Solidity syntax. State variables, functions, modifiers. First smart contract.", type: "video" },
      { title: "Smart Contracts: Security Best Practices", content: "Reentrancy, overflow/underflow, common vulnerabilities. Secure code patterns.", type: "video" },
      { title: "Quiz: Blockchain & Solidity Fundamentals", content: "12 questions on smart contracts and security.", type: "quiz" },
      { title: "DeFi Protocols: Lending, Staking, Swaps", content: "How DeFi works. Uniswap, Aave, Curve. Financial primitives.", type: "video" },
      { title: "Building a Token Contract: ERC-20 & ERC-721", content: "Fungible tokens (ERC-20). Non-fungible tokens (NFTs, ERC-721). Deployment.", type: "video" },
      { title: "Real Project: Build a Decentralized Marketplace", content: "Smart contracts, frontend (Web3.js), user wallet integration. Full dApp.", type: "video" },
      { title: "Gas Optimization: Writing Efficient Contracts", content: "Reduce gas costs. Optimization techniques. Cost matters for users.", type: "video" },
      { title: "Real Case Study: Blockchain Dev Earns R120k/Month", content: "Dev learned Solidity → freelanced contracts → R120k/month. Demand is huge.", type: "text" },
      { title: "Testing & Auditing Smart Contracts", content: "Unit tests, integration tests, security audits. Production-ready code.", type: "video" },
      { title: "Deploying to Mainnet: Moving to Production", content: "Testnet → Mainnet. Gas fees, slippage, real-world considerations.", type: "video" },
      { title: "DeFi Yield Farming & Staking", content: "How yield farming works. APY calculations. Impermanent loss. Risk management.", type: "text" },
      { title: "NFTs Beyond Art: Utility & Communities", content: "NFTs for membership, access, credentials. Real-world use cases.", type: "video" },
      { title: "Quiz: Advanced Web3 & DeFi", content: "15 advanced questions on contracts, DeFi, NFTs.", type: "quiz" },
      { title: "Web3 Frontend: Connecting Wallets, Reading Contracts", content: "Web3.js, ethers.js, connecting MetaMask. Read/write contract functions.", type: "video" },
      { title: "Multi-Chain Development: Polygon, Arbitrum, Optimism", content: "Deploy to layer 2s, sidechains. Polygon ecosystem. Cost-effective scaling.", type: "video" },
      { title: "Real Freelance Project: Build a Complete dApp", content: "Smart contract + frontend + deployment. End-to-end project.", type: "video" },
      { title: "Career Path: From Solidity Dev to Protocol Lead", content: "Progression opportunities. DAO participation. Founding startups.", type: "text" },
      { title: "Final Project: Deploy Your Smart Contract", content: "Build, test, audit, deploy to testnet. Client-ready smart contract.", type: "quiz" },
    ],
    quiz: []
  },

  // ── SOFT SKILLS ────────────────────────────────────────────────────────────
  {
    title: "Time Management & Productivity: Work Less, Earn More",
    description: "Master your time. 4-hour workday. Automate everything. Earn premium rates for fewer hours. Work/life balance.",
    category: "Business Development",
    difficulty: "beginner",
    duration: "5 hours",
    totalLessons: 10,
    isFree: true,
    skillsTaught: ["Time Management", "Productivity", "Automation", "Systems"],
    earningsLiftPct: 40,
    lessons: [
      { title: "The 80/20 Rule: Focus on What Matters", content: "Pareto principle. Identify your 20% high-impact activities. Eliminate the rest.", type: "video" },
      { title: "Time Blocking: Structure Your Day", content: "Deep work blocks, shallow work, admin time. Calendar-based planning.", type: "video" },
      { title: "Batch Processing: Do Like Things Together", content: "Emails, calls, admin in blocks. Focus on one type of work. Reduce context switching.", type: "video" },
      { title: "Automation Tools: Zapier, IFTTT, Shortcuts", content: "Automate repetitive tasks. Save 10+ hours/week. Leverage technology.", type: "video" },
      { title: "Quiz: Time Management Fundamentals", content: "7 questions on prioritization and automation.", type: "quiz" },
      { title: "Systems & Processes: Build Your Playbook", content: "Document everything. Standard operating procedures. Scalable workflows.", type: "video" },
      { title: "Delegation: When to Do It Yourself vs Outsource", content: "Cost of your time. When to hire. VA, agencies, contractors.", type: "video" },
      { title: "Real Case Study: Freelancer Works 20 Hours/Week", content: "Dev works only mornings. Processes automated. Earns R80k/month. Rest of week free.", type: "text" },
      { title: "Energy Management: When You're Most Productive", content: "Your biological peak hours. Protect them. Default to deep work time.", type: "text" },
      { title: "Final Project: Redesign Your Week", content: "Audit current schedule. Implement time blocking. Automate 3 tasks. Measure impact.", type: "quiz" },
    ],
    quiz: []
  },

  {
    title: "Public Speaking & Pitching: Own the Room",
    description: "Overcome nervousness. Deliver powerful presentations. Pitch clients with confidence. Win more deals through voice.",
    category: "Business Development",
    difficulty: "beginner",
    duration: "6 hours",
    totalLessons: 11,
    isFree: true,
    skillsTaught: ["Public Speaking", "Presentation", "Pitch Skills", "Confidence"],
    earningsLiftPct: 50,
    lessons: [
      { title: "Nervous System: Controlling Anxiety", content: "Physical techniques to calm nerves. Breathing exercises. Visualization. Real neuroscience.", type: "video" },
      { title: "Story Structure: The Hero's Journey", content: "Classic story arc. Setup, conflict, resolution. Hook people emotionally.", type: "video" },
      { title: "Pitch Structure: 60 Seconds to Win a Client", content: "Elevator pitch formula. Opening hook, problem, solution, ask. Real examples.", type: "video" },
      { title: "Slide Design: Less is More", content: "Minimalist slides. No bullet points. One idea per slide. Visuals over text.", type: "video" },
      { title: "Quiz: Speaking & Pitching Fundamentals", content: "8 questions on structure and delivery.", type: "quiz" },
      { title: "Body Language: Stand, Move, Gesture", content: "Stage presence. Eye contact. Power postures. Non-verbal communication.", type: "video" },
      { title: "Vocal Delivery: Pace, Tone, Emphasis", content: "Speak confidently. Vary pace. Pause for emphasis. Vocal confidence.", type: "video" },
      { title: "Q&A Handling: The Dangerous Part", content: "Prepare for tough questions. Reframe objections. Think on your feet.", type: "video" },
      { title: "Real Case Study: Won R300k Project with a Pitch", content: "Freelancer pitched to a large client. Perfect pitch, right story. Won the project.", type: "text" },
      { title: "Presenting Data Effectively", content: "Make numbers tell a story. Avoid death by data. Impactful data visualization.", type: "text" },
      { title: "Final Project: Record Your Pitch", content: "Write, rehearse, record your 60-second pitch. Get feedback. Practice.", type: "quiz" },
    ],
    quiz: []
  },
];

// 50+ courses covering all major freelance skills
// Africa-first pricing (ZAR), POPIA compliant, earnings-lift proven
// Each course has lessons, quizzes, real case studies, downloadable resources
