// Server-side academy course metadata
// Mirrors client/src/lib/academyCurriculum.ts (metadata only — no lesson content)
// This file is imported by server/routes.ts for the /api/academy/* endpoints

export interface CourseMetadata {
  id: number;
  slug: string;
  title: string;
  tagline: string;
  description: string;
  category: string;
  difficulty: "Beginner" | "Intermediate" | "Advanced";
  duration: string;
  earningsLift: string;
  skills: string[];
  isFree: boolean;
  rating: number;
  enrolled: number;
  color: string;
  emoji: string;
  moduleCount: number;
  lessonCount: number;
}

export const ACADEMY_COURSES: CourseMetadata[] = [
  {
    id: 1,
    slug: "ai-prompt-engineering",
    title: "AI Prompt Engineering Masterclass",
    tagline: "Master ChatGPT, Claude & Grok to 10× your freelance output.",
    description: "Learn how to craft prompts that produce professional-quality work in seconds. This course transforms how you use AI tools for proposals, content, code, and client work.",
    category: "AI & Machine Learning",
    difficulty: "Beginner",
    duration: "4 hours",
    earningsLift: "+45%",
    skills: ["AI Prompting", "ChatGPT", "Claude", "Productivity"],
    isFree: true,
    rating: 4.9,
    enrolled: 12400,
    color: "from-violet-600 to-purple-700",
    emoji: "🤖",
    moduleCount: 4,
    lessonCount: 12,
  },
  {
    id: 2,
    slug: "no-code-automation",
    title: "No-Code Automation: Zapier & Make.com",
    tagline: "Automate your freelance business without writing a single line of code.",
    description: "Build powerful automated workflows that handle repetitive tasks, nurture leads, send invoices, and manage clients — all on autopilot.",
    category: "AI & Machine Learning",
    difficulty: "Beginner",
    duration: "3 hours",
    earningsLift: "+35%",
    skills: ["Zapier", "Make.com", "Automation", "Workflow"],
    isFree: true,
    rating: 4.8,
    enrolled: 8300,
    color: "from-orange-500 to-amber-600",
    emoji: "⚡",
    moduleCount: 4,
    lessonCount: 10,
  },
  {
    id: 3,
    slug: "react-nextjs",
    title: "React + Next.js: Build & Deploy Real Projects",
    tagline: "Build full-stack apps that land R20,000+ projects.",
    description: "Go from React basics to production-ready Next.js apps with real-world projects. Master hooks, API routes, authentication, and deployment.",
    category: "Web Development",
    difficulty: "Intermediate",
    duration: "20 hours",
    earningsLift: "+120%",
    skills: ["React", "Next.js", "TypeScript", "Full-Stack"],
    isFree: false,
    rating: 4.9,
    enrolled: 6800,
    color: "from-blue-600 to-cyan-600",
    emoji: "⚛️",
    moduleCount: 5,
    lessonCount: 18,
  },
  {
    id: 4,
    slug: "figma-freelancers",
    title: "Figma for Freelancers",
    tagline: "Design stunning websites and apps. Charge R15,000+ per project.",
    description: "Master Figma from basics to professional UI/UX design. Build a portfolio that lands design clients.",
    category: "Graphic Design",
    difficulty: "Beginner",
    duration: "10 hours",
    earningsLift: "+65%",
    skills: ["Figma", "UI Design", "Prototyping", "Design Systems"],
    isFree: true,
    rating: 4.8,
    enrolled: 9100,
    color: "from-pink-600 to-rose-600",
    emoji: "🎨",
    moduleCount: 4,
    lessonCount: 14,
  },
  {
    id: 5,
    slug: "high-converting-copywriting",
    title: "High-Converting Copywriting",
    tagline: "Write proposals that win. Land clients on the first try.",
    description: "Master the psychology of persuasion, proposal writing, and client communication that wins R50k+ projects.",
    category: "Copywriting",
    difficulty: "Beginner",
    duration: "6 hours",
    earningsLift: "+55%",
    skills: ["Copywriting", "Persuasion", "Proposals", "Client Psychology"],
    isFree: true,
    rating: 4.7,
    enrolled: 7200,
    color: "from-yellow-500 to-orange-500",
    emoji: "✍️",
    moduleCount: 4,
    lessonCount: 12,
  },
  {
    id: 6,
    slug: "google-ads-mastery",
    title: "Google Ads Mastery",
    tagline: "Spend R5, get R50. Master Google Search Ads for SA businesses.",
    description: "Learn to plan, build, and optimise profitable Google Ads campaigns for South African businesses. Get certified.",
    category: "Digital Marketing",
    difficulty: "Intermediate",
    duration: "14 hours",
    earningsLift: "+120%",
    skills: ["Google Ads", "PPC", "Analytics", "CRO"],
    isFree: false,
    rating: 4.9,
    enrolled: 4200,
    color: "from-red-500 to-orange-600",
    emoji: "📈",
    moduleCount: 4,
    lessonCount: 14,
  },
  {
    id: 7,
    slug: "personal-branding",
    title: "Personal Branding: Become Unforgettable",
    tagline: "Build a personal brand that attracts premium clients on autopilot.",
    description: "Learn how to position yourself, create compelling LinkedIn content, and build authority that commands premium rates.",
    category: "Business Development",
    difficulty: "Beginner",
    duration: "7 hours",
    earningsLift: "+70%",
    skills: ["LinkedIn", "Personal Branding", "Content Strategy", "Authority"],
    isFree: true,
    rating: 4.8,
    enrolled: 10500,
    color: "from-indigo-600 to-blue-600",
    emoji: "⭐",
    moduleCount: 4,
    lessonCount: 12,
  },
  {
    id: 8,
    slug: "data-analytics-python-sql",
    title: "Data Analytics with Python & SQL",
    tagline: "Master Python, SQL, and data viz. Land R30-50k/month contracts.",
    description: "From zero to professional data analyst. Learn Python pandas, SQL queries, Power BI, and data storytelling for the South African market.",
    category: "Data Analytics",
    difficulty: "Intermediate",
    duration: "24 hours",
    earningsLift: "+140%",
    skills: ["Python", "SQL", "Power BI", "Pandas", "Data Viz"],
    isFree: false,
    rating: 4.9,
    enrolled: 3800,
    color: "from-teal-600 to-emerald-600",
    emoji: "📊",
    moduleCount: 5,
    lessonCount: 18,
  },
  {
    id: 9,
    slug: "high-ticket-sales",
    title: "High-Ticket Sales: Closing R50k+ Projects",
    tagline: "Land R50,000–500,000 contracts using proven sales psychology.",
    description: "Master discovery calls, objection handling, and closing techniques to consistently land high-value freelance contracts.",
    category: "Business Development",
    difficulty: "Advanced",
    duration: "10 hours",
    earningsLift: "+200%",
    skills: ["Sales", "Negotiation", "Discovery", "Closing"],
    isFree: false,
    rating: 4.9,
    enrolled: 2900,
    color: "from-emerald-600 to-teal-600",
    emoji: "💎",
    moduleCount: 4,
    lessonCount: 12,
  },
  {
    id: 10,
    slug: "content-marketing",
    title: "Content Marketing: Build Authority",
    tagline: "Blog, LinkedIn, YouTube: become the go-to expert in your niche.",
    description: "Build a content marketing machine that generates leads on autopilot. Learn SEO, content strategy, distribution, and monetisation.",
    category: "Digital Marketing",
    difficulty: "Intermediate",
    duration: "12 hours",
    earningsLift: "+85%",
    skills: ["Content Strategy", "SEO", "LinkedIn", "Blogging"],
    isFree: false,
    rating: 4.7,
    enrolled: 5100,
    color: "from-purple-600 to-indigo-600",
    emoji: "📝",
    moduleCount: 4,
    lessonCount: 14,
  },
  {
    id: 11,
    slug: "responsive-web-design",
    title: "Responsive Web Design & Mobile-First",
    tagline: "Master CSS Grid, Flexbox, and build beautiful websites.",
    description: "Build professional, responsive websites from scratch. Learn HTML, CSS, Tailwind, and mobile-first design principles.",
    category: "Web Development",
    difficulty: "Beginner",
    duration: "8 hours",
    earningsLift: "+40%",
    skills: ["HTML", "CSS", "Tailwind CSS", "Responsive Design"],
    isFree: true,
    rating: 4.7,
    enrolled: 11200,
    color: "from-sky-600 to-blue-700",
    emoji: "🌐",
    moduleCount: 4,
    lessonCount: 12,
  },
  {
    id: 12,
    slug: "video-editing",
    title: "Video Editing: DaVinci Resolve & Premiere",
    tagline: "Edit YouTube, social, and corporate videos. Land R8,000+ projects.",
    description: "Learn professional video editing from scratch using DaVinci Resolve (free) and Adobe Premiere. Build a video editing practice.",
    category: "Video & Animation",
    difficulty: "Beginner",
    duration: "12 hours",
    earningsLift: "+75%",
    skills: ["DaVinci Resolve", "Adobe Premiere", "Color Grading", "Audio"],
    isFree: true,
    rating: 4.6,
    enrolled: 6700,
    color: "from-red-600 to-pink-600",
    emoji: "🎬",
    moduleCount: 4,
    lessonCount: 12,
  },
  {
    id: 13,
    slug: "time-management-productivity",
    title: "Time Management & Productivity for Freelancers",
    tagline: "4-hour effective workday. Earn more by working less.",
    description: "Master time blocking, the Pomodoro technique, AI-assisted workflows, and systems thinking to maximise your freelance output.",
    category: "Business Development",
    difficulty: "Beginner",
    duration: "5 hours",
    earningsLift: "+40%",
    skills: ["Time Management", "Productivity", "Systems", "Automation"],
    isFree: true,
    rating: 4.6,
    enrolled: 13400,
    color: "from-green-600 to-emerald-700",
    emoji: "⏰",
    moduleCount: 3,
    lessonCount: 10,
  },
  {
    id: 14,
    slug: "public-speaking-pitching",
    title: "Public Speaking & Client Pitching",
    tagline: "Own the room. Pitch with confidence. Win every presentation.",
    description: "Transform from nervous presenter to confident communicator. Master pitching to clients, presenting to boardrooms, and commanding any room.",
    category: "Business Development",
    difficulty: "Beginner",
    duration: "6 hours",
    earningsLift: "+50%",
    skills: ["Public Speaking", "Presenting", "Pitching", "Confidence"],
    isFree: true,
    rating: 4.5,
    enrolled: 8900,
    color: "from-amber-500 to-yellow-600",
    emoji: "🎤",
    moduleCount: 3,
    lessonCount: 10,
  },
  {
    id: 15,
    slug: "blockchain-solidity-web3",
    title: "Blockchain Development: Solidity & Web3",
    tagline: "Build smart contracts, DeFi apps, and NFT platforms.",
    description: "Master Solidity smart contract development, Web3 integration, and blockchain fundamentals to land premium Web3 contracts.",
    category: "Web Development",
    difficulty: "Advanced",
    duration: "30 hours",
    earningsLift: "+200%",
    skills: ["Solidity", "Smart Contracts", "Web3", "Ethereum"],
    isFree: false,
    rating: 4.8,
    enrolled: 2100,
    color: "from-violet-700 to-purple-800",
    emoji: "⛓️",
    moduleCount: 5,
    lessonCount: 18,
  },
];

export function getAcademyStats() {
  const totalCourses = ACADEMY_COURSES.length;
  const freeCourses = ACADEMY_COURSES.filter((c) => c.isFree).length;
  const totalEnrolments = ACADEMY_COURSES.reduce((s, c) => s + c.enrolled, 0);
  const totalLessons = ACADEMY_COURSES.reduce((s, c) => s + c.lessonCount, 0);
  const totalModules = ACADEMY_COURSES.reduce((s, c) => s + c.moduleCount, 0);
  const avgRating = (ACADEMY_COURSES.reduce((s, c) => s + c.rating, 0) / totalCourses).toFixed(1);
  return { totalCourses, freeCourses, totalEnrolments, totalLessons, totalModules, avgRating, avgCompletionRate: "94.8" };
}
