import type { AdminModuleKey } from "@/types/admin";
import type { AdminColumn } from "@/components/admin/ui/AdminDataTable";

export const ADMIN_MODULE_COLUMNS: Record<AdminModuleKey, AdminColumn[]> = {
  overview: [
    { key: "title", label: "Title" },
    { key: "status", label: "Status", type: "status" },
    { key: "createdAt", label: "Created", type: "date" },
  ],
  users: [
    { key: "title", label: "User" },
    { key: "subtitle", label: "Role" },
    { key: "location", label: "Location" },
    { key: "planType", label: "Plan" },
    { key: "status", label: "Status", type: "status" },
    { key: "createdAt", label: "Joined", type: "date" },
  ],
  freelancers: [
    { key: "title", label: "Freelancer" },
    { key: "subtitle", label: "Specialty" },
    { key: "location", label: "Location" },
    { key: "amount", label: "Rate", type: "currency" },
    { key: "status", label: "Verification", type: "status" },
  ],
  clients: [
    { key: "title", label: "Client" },
    { key: "subtitle", label: "Activity" },
    { key: "location", label: "Location" },
    { key: "amount", label: "Spend", type: "currency" },
    { key: "status", label: "Status", type: "status" },
  ],
  jobs: [
    { key: "title", label: "Job" },
    { key: "subtitle", label: "Category" },
    { key: "location", label: "Location" },
    { key: "amount", label: "Budget", type: "currency" },
    { key: "status", label: "Status", type: "status" },
    { key: "createdAt", label: "Posted", type: "date" },
  ],
  jobApplications: [
    { key: "title", label: "Application" },
    { key: "subtitle", label: "Applicant" },
    { key: "location", label: "Location" },
    { key: "status", label: "Status", type: "status" },
    { key: "createdAt", label: "Applied", type: "date" },
  ],
  services: [
    { key: "title", label: "Service" },
    { key: "subtitle", label: "Category" },
    { key: "location", label: "Location" },
    { key: "amount", label: "From", type: "currency" },
    { key: "status", label: "Status", type: "status" },
  ],
  taskers: [
    { key: "title", label: "Tasker" },
    { key: "subtitle", label: "Category" },
    { key: "location", label: "Location" },
    { key: "amount", label: "Rate", type: "currency" },
    { key: "status", label: "Availability", type: "status" },
  ],
  bookings: [
    { key: "title", label: "Booking" },
    { key: "subtitle", label: "Service" },
    { key: "location", label: "Location" },
    { key: "amount", label: "Value", type: "currency" },
    { key: "status", label: "Status", type: "status" },
    { key: "createdAt", label: "Created", type: "date" },
  ],
  serviceRequests: [
    { key: "title", label: "Request" },
    { key: "subtitle", label: "Category" },
    { key: "location", label: "Location" },
    { key: "status", label: "Pipeline", type: "status" },
    { key: "createdAt", label: "Received", type: "date" },
  ],
  payments: [
    { key: "title", label: "Payment" },
    { key: "subtitle", label: "Type" },
    { key: "amount", label: "Amount", type: "currency" },
    { key: "status", label: "Status", type: "status" },
    { key: "createdAt", label: "Date", type: "date" },
  ],
  subscriptions: [
    { key: "title", label: "Subscriber" },
    { key: "planType", label: "Plan" },
    { key: "status", label: "Status", type: "status" },
    { key: "createdAt", label: "Started", type: "date" },
  ],
  messages: [
    { key: "title", label: "Conversation" },
    { key: "subtitle", label: "Context" },
    { key: "status", label: "State", type: "status" },
    { key: "updatedAt", label: "Updated", type: "date" },
  ],
  support: [
    { key: "title", label: "Ticket" },
    { key: "priority", label: "Priority" },
    { key: "status", label: "Status", type: "status" },
    { key: "updatedAt", label: "Updated", type: "date" },
  ],
  reports: [
    { key: "title", label: "Report" },
    { key: "subtitle", label: "Reported by" },
    { key: "priority", label: "Priority" },
    { key: "status", label: "Status", type: "status" },
    { key: "createdAt", label: "Created", type: "date" },
  ],
  moderation: [
    { key: "title", label: "Queue Item" },
    { key: "subtitle", label: "Reason" },
    { key: "priority", label: "Priority" },
    { key: "status", label: "Status", type: "status" },
    { key: "createdAt", label: "Submitted", type: "date" },
  ],
  disputes: [
    { key: "title", label: "Dispute" },
    { key: "subtitle", label: "Case" },
    { key: "amount", label: "Amount", type: "currency" },
    { key: "status", label: "Status", type: "status" },
    { key: "createdAt", label: "Opened", type: "date" },
  ],
  fraud: [
    { key: "title", label: "Risk Event" },
    { key: "subtitle", label: "Pattern" },
    { key: "riskScore", label: "Risk Score", type: "number" },
    { key: "status", label: "Status", type: "status" },
    { key: "createdAt", label: "Detected", type: "date" },
  ],
  notifications: [
    { key: "title", label: "Notification" },
    { key: "subtitle", label: "Audience" },
    { key: "status", label: "State", type: "status" },
    { key: "createdAt", label: "Created", type: "date" },
  ],
  categories: [
    { key: "title", label: "Category" },
    { key: "subtitle", label: "Description" },
    { key: "status", label: "Status", type: "status" },
    { key: "createdAt", label: "Updated", type: "date" },
  ],
  promotions: [
    { key: "title", label: "Promotion" },
    { key: "subtitle", label: "Campaign" },
    { key: "status", label: "Status", type: "status" },
    { key: "createdAt", label: "Launched", type: "date" },
  ],
  cms: [
    { key: "title", label: "Content Block" },
    { key: "subtitle", label: "Section" },
    { key: "status", label: "Publish Status", type: "status" },
    { key: "updatedAt", label: "Updated", type: "date" },
  ],
  analytics: [
    { key: "title", label: "Snapshot" },
    { key: "subtitle", label: "Summary" },
    { key: "status", label: "Status", type: "status" },
    { key: "createdAt", label: "Generated", type: "date" },
  ],
  featureFlags: [
    { key: "title", label: "Feature" },
    { key: "subtitle", label: "Rollout" },
    { key: "status", label: "Status", type: "status" },
    { key: "updatedAt", label: "Updated", type: "date" },
  ],
  roles: [
    { key: "title", label: "Role" },
    { key: "subtitle", label: "Permissions" },
    { key: "status", label: "Status", type: "status" },
    { key: "updatedAt", label: "Updated", type: "date" },
  ],
  adminUsers: [
    { key: "title", label: "Admin User" },
    { key: "subtitle", label: "Role" },
    { key: "status", label: "Status", type: "status" },
    { key: "updatedAt", label: "Updated", type: "date" },
  ],
  auditLogs: [
    { key: "title", label: "Action" },
    { key: "subtitle", label: "Actor" },
    { key: "status", label: "Outcome", type: "status" },
    { key: "createdAt", label: "Date", type: "date" },
  ],
  security: [
    { key: "title", label: "Security Event" },
    { key: "subtitle", label: "Context" },
    { key: "status", label: "Status", type: "status" },
    { key: "createdAt", label: "Detected", type: "date" },
  ],
  systemSettings: [
    { key: "title", label: "Setting" },
    { key: "subtitle", label: "Value" },
    { key: "status", label: "Status", type: "status" },
    { key: "updatedAt", label: "Updated", type: "date" },
  ],
  monitoring: [
    { key: "title", label: "Signal" },
    { key: "subtitle", label: "Reading" },
    { key: "status", label: "Health", type: "status" },
    { key: "updatedAt", label: "Updated", type: "date" },
  ],
  aiTools: [
    { key: "title", label: "AI Module" },
    { key: "subtitle", label: "Model / Function" },
    { key: "status", label: "Status", type: "status" },
    { key: "updatedAt", label: "Updated", type: "date" },
  ],
  missionControl: [
    { key: "title", label: "Incident" },
    { key: "subtitle", label: "Summary" },
    { key: "priority", label: "Priority" },
    { key: "status", label: "Status", type: "status" },
    { key: "createdAt", label: "Detected", type: "date" },
  ],
};
