import type { AdminModuleMeta, AdminPermission, AdminRole } from "@/types/admin";

const ALL_PERMISSIONS: AdminPermission[] = [
  "overview.read",
  "users.read", "users.manage",
  "freelancers.read", "freelancers.manage",
  "clients.read", "clients.manage",
  "jobs.read", "jobs.manage",
  "applications.read", "applications.manage",
  "services.read", "services.manage",
  "taskers.read", "taskers.manage",
  "bookings.read", "bookings.manage",
  "serviceRequests.read", "serviceRequests.manage",
  "payments.read", "payments.manage",
  "subscriptions.read", "subscriptions.manage",
  "messages.read", "messages.manage",
  "support.read", "support.manage",
  "reports.read", "reports.manage",
  "moderation.read", "moderation.manage",
  "disputes.read", "disputes.manage",
  "fraud.read", "fraud.manage",
  "notifications.read", "notifications.manage",
  "categories.read", "categories.manage",
  "promotions.read", "promotions.manage",
  "cms.read", "cms.manage",
  "analytics.read",
  "featureFlags.read", "featureFlags.manage",
  "roles.read", "roles.manage",
  "adminUsers.read", "adminUsers.manage",
  "auditLogs.read",
  "security.read", "security.manage",
  "systemSettings.read", "systemSettings.manage",
  "monitoring.read",
  "aiTools.read", "aiTools.manage",
  "missionControl.read", "missionControl.manage",
];

const READ_ONLY: AdminPermission[] = ALL_PERMISSIONS.filter((p) => p.endsWith(".read") || p === "analytics.read");

export const ROLE_PERMISSIONS: Record<AdminRole, AdminPermission[]> = {
  super_admin: ALL_PERMISSIONS,
  operations_admin: [
    "overview.read",
    "users.read", "users.manage",
    "freelancers.read", "freelancers.manage",
    "clients.read", "clients.manage",
    "jobs.read", "jobs.manage",
    "applications.read", "applications.manage",
    "services.read", "services.manage",
    "taskers.read", "taskers.manage",
    "bookings.read", "bookings.manage",
    "serviceRequests.read", "serviceRequests.manage",
    "messages.read", "messages.manage",
    "support.read", "support.manage",
    "reports.read", "reports.manage",
    "moderation.read", "moderation.manage",
    "disputes.read", "disputes.manage",
    "fraud.read", "fraud.manage",
    "categories.read", "categories.manage",
    "analytics.read",
    "monitoring.read",
    "missionControl.read",
  ],
  finance_admin: [
    "overview.read",
    "payments.read", "payments.manage",
    "subscriptions.read", "subscriptions.manage",
    "bookings.read", "bookings.manage",
    "serviceRequests.read", "serviceRequests.manage",
    "disputes.read", "disputes.manage",
    "fraud.read", "fraud.manage",
    "auditLogs.read",
    "analytics.read",
    "systemSettings.read",
    "monitoring.read",
  ],
  support_admin: [
    "overview.read",
    "users.read",
    "messages.read", "messages.manage",
    "support.read", "support.manage",
    "reports.read", "reports.manage",
    "disputes.read", "disputes.manage",
    "notifications.read", "notifications.manage",
    "auditLogs.read",
    "analytics.read",
  ],
  moderation_admin: [
    "overview.read",
    "users.read", "users.manage",
    "jobs.read", "jobs.manage",
    "applications.read", "applications.manage",
    "services.read", "services.manage",
    "taskers.read", "taskers.manage",
    "reports.read", "reports.manage",
    "moderation.read", "moderation.manage",
    "disputes.read", "disputes.manage",
    "fraud.read", "fraud.manage",
    "auditLogs.read",
    "security.read", "security.manage",
  ],
  marketing_admin: [
    "overview.read",
    "users.read",
    "services.read", "services.manage",
    "notifications.read", "notifications.manage",
    "promotions.read", "promotions.manage",
    "cms.read", "cms.manage",
    "categories.read", "categories.manage",
    "analytics.read",
    "featureFlags.read",
    "aiTools.read",
  ],
  academy_admin: [
    "overview.read",
    "users.read",
    "freelancers.read",
    "clients.read",
    "notifications.read",
    "cms.read", "cms.manage",
    "categories.read",
    "analytics.read",
  ],
  analyst: READ_ONLY,
};

export const ADMIN_MODULES: AdminModuleMeta[] = [
  { key: "overview", title: "Overview", description: "Executive platform health dashboard", path: "/admin/overview", readPermission: "overview.read" },
  { key: "users", title: "Users", description: "Manage all platform accounts", path: "/admin/users", readPermission: "users.read", managePermission: "users.manage", collection: "users" },
  { key: "freelancers", title: "Freelancers", description: "Freelancer profiles and verification", path: "/admin/freelancers", readPermission: "freelancers.read", managePermission: "freelancers.manage", collection: "freelancerProfiles" },
  { key: "clients", title: "Clients", description: "Client account operations", path: "/admin/clients", readPermission: "clients.read", managePermission: "clients.manage", collection: "users" },
  { key: "jobs", title: "Jobs", description: "Job posting lifecycle management", path: "/admin/jobs", readPermission: "jobs.read", managePermission: "jobs.manage", collection: "jobs" },
  { key: "jobApplications", title: "Job Applications", description: "Review and triage job applications", path: "/admin/job-applications", readPermission: "applications.read", managePermission: "applications.manage", collection: "jobApplications" },
  { key: "services", title: "Services", description: "Service catalog operations", path: "/admin/services", readPermission: "services.read", managePermission: "services.manage", collection: "services" },
  { key: "taskers", title: "Taskers", description: "Tasker quality and availability", path: "/admin/taskers", readPermission: "taskers.read", managePermission: "taskers.manage", collection: "taskers" },
  { key: "bookings", title: "Bookings", description: "Booking pipeline and interventions", path: "/admin/bookings", readPermission: "bookings.read", managePermission: "bookings.manage", collection: "bookings" },
  { key: "serviceRequests", title: "Service Requests", description: "Incoming service demand queue", path: "/admin/service-requests", readPermission: "serviceRequests.read", managePermission: "serviceRequests.manage", collection: "serviceRequests" },
  { key: "payments", title: "Payments", description: "Transactions and payment statuses", path: "/admin/payments", readPermission: "payments.read", managePermission: "payments.manage", collection: "payments" },
  { key: "subscriptions", title: "Subscriptions", description: "Plan and subscription controls", path: "/admin/subscriptions", readPermission: "subscriptions.read", managePermission: "subscriptions.manage", collection: "users" },
  { key: "messages", title: "Messages", description: "Conversation oversight", path: "/admin/messages", readPermission: "messages.read", managePermission: "messages.manage", collection: "supportChats" },
  { key: "support", title: "Support", description: "Ticket and support operations", path: "/admin/support", readPermission: "support.read", managePermission: "support.manage", collection: "supportChats" },
  { key: "reports", title: "Reports", description: "Abuse and report handling", path: "/admin/reports", readPermission: "reports.read", managePermission: "reports.manage", collection: "reports" },
  { key: "moderation", title: "Moderation", description: "Content and account moderation queue", path: "/admin/moderation", readPermission: "moderation.read", managePermission: "moderation.manage", collection: "moderationQueue" },
  { key: "disputes", title: "Disputes", description: "Dispute resolution pipeline", path: "/admin/disputes", readPermission: "disputes.read", managePermission: "disputes.manage", collection: "disputes" },
  { key: "fraud", title: "Fraud", description: "Risk signals and fraud actions", path: "/admin/fraud", readPermission: "fraud.read", managePermission: "fraud.manage", collection: "fraudEvents" },
  { key: "notifications", title: "Notifications", description: "Announcements and communication operations", path: "/admin/notifications", readPermission: "notifications.read", managePermission: "notifications.manage", collection: "notifications" },
  { key: "categories", title: "Categories", description: "Taxonomy and skill tags", path: "/admin/categories", readPermission: "categories.read", managePermission: "categories.manage", collection: "categories" },
  { key: "promotions", title: "Promotions", description: "Campaigns and featured placement", path: "/admin/promotions", readPermission: "promotions.read", managePermission: "promotions.manage", collection: "promotions" },
  { key: "cms", title: "CMS", description: "Content and landing management", path: "/admin/cms", readPermission: "cms.read", managePermission: "cms.manage", collection: "cms" },
  { key: "analytics", title: "Analytics", description: "Marketplace and growth analytics", path: "/admin/analytics", readPermission: "analytics.read", collection: "analyticsSnapshots" },
  { key: "featureFlags", title: "Feature Flags", description: "Controlled rollout and runtime toggles", path: "/admin/feature-flags", readPermission: "featureFlags.read", managePermission: "featureFlags.manage", collection: "featureFlags" },
  { key: "roles", title: "Roles", description: "Permission templates and assignments", path: "/admin/roles", readPermission: "roles.read", managePermission: "roles.manage", collection: "roles" },
  { key: "adminUsers", title: "Admin Users", description: "Internal admin account management", path: "/admin/admin-users", readPermission: "adminUsers.read", managePermission: "adminUsers.manage", collection: "adminUsers" },
  { key: "auditLogs", title: "Audit Logs", description: "Who changed what and when", path: "/admin/audit-logs", readPermission: "auditLogs.read", collection: "auditLogs" },
  { key: "security", title: "Security", description: "Security posture and controls", path: "/admin/security", readPermission: "security.read", managePermission: "security.manage", collection: "securityEvents" },
  { key: "systemSettings", title: "System Settings", description: "Platform runtime preferences", path: "/admin/system-settings", readPermission: "systemSettings.read", managePermission: "systemSettings.manage", collection: "systemSettings" },
  { key: "monitoring", title: "Monitoring", description: "Performance and infrastructure status", path: "/admin/monitoring", readPermission: "monitoring.read", collection: "monitoringSnapshots" },
  { key: "aiTools", title: "AI Tools", description: "AI moderation and recommendation controls", path: "/admin/ai-tools", readPermission: "aiTools.read", managePermission: "aiTools.manage", collection: "aiTools" },
  { key: "missionControl", title: "Mission Control", description: "Cross-domain command center", path: "/admin/mission-control", readPermission: "missionControl.read", managePermission: "missionControl.manage", collection: "incidents" },
];

export function hasPermission(permissions: AdminPermission[], permission: AdminPermission) {
  return permissions.includes(permission);
}

export function permissionsForRole(role: AdminRole): AdminPermission[] {
  return ROLE_PERMISSIONS[role] || READ_ONLY;
}
